Bugfix/js exc johan pinares
makeitrealcamp/top-fs-dev-proinnovate-i-2024 pull request #59
Opened 2024-09-03 16:24 UTC by JohanEmersonPinares

### Descripción
[//]: <> (Aca debe ir la descripcion del PullRequest, que es? que hace?)
Se verifico los ejercicios referente a javascript resolviendo algunos errores presentados en el codigo aumentando cosas para obtener el resultado que se queria

### Feeling
[//]: <> (Como te sientes con este PR? la solucion que entregas como te hace sentir?)
- [ ] 🤙 Solucion rapida
- [x] 👌 Terminado y listo
- [ ] 🤞 Espero que esto funcione, por favor revisar cuidadosamente

### Tickets
[//]: <> (El numero del ticket asociado a este PR)

### Cómo probar?
[//]: <> (Pasos necesarios para probar esta funcionalidad)
descargar archivo y compilar para comprobar resultados 
### Screenshots (si es aplicable)
[//]: <> (Capturas de pantalla que ayuden a entender que hiciste en este PR)

### Scope

- [ ] 🐞 Bugfix (non-breaking changes que resuelve un problema
- [ ] 💚 Mejora (non-breaking change que agrega/modifica funcionalidad a una característica existente)
- [ ] ⚡️ Nueva característica/feature (non-breaking change que agrega una nueva característica)
- [ ] ⚠️ Breaking change (cambio que no es compatible con versiones anteriores y/o cambia la funcionalidad actual)

2024-09-03 19:52 UTC, khriztianmoreno requested changes
Por favor corrige los nombres los archivos, deben ser validos, sin esapcios, en minusculas y sin tidles

2024-09-03 22:37 UTC, GersonSmithKevin approved these changes

2024-09-04 18:02 UTC, nayruthCalla approved these changes

2024-09-04 22:48 UTC, nayruthCalla approved these changes

2024-09-05 14:52 UTC, merged