feature: CREATE Bugfix/js-exc-juan-alva
makeitrealcamp/top-fs-dev-proinnovate-i-2024 pull request #67
Opened 2024-09-03 21:27 UTC by jlac8

### Descripción
Resolución de los Bug Fixes y con los commits correspondientes.

### Feeling
[//]: <> (Como te sientes con este PR? la solucion que entregas como te hace sentir?)
- [ ] 🤙 Solucion rapida
- [x ] 👌 Terminado y listo
- [ ] 🤞 Espero que esto funcione, por favor revisar cuidadosamente

### Screenshots (si es aplicable)
![image](https://github.com/user-attachments/assets/c799a1e2-09e2-4a22-a618-05361771cc6e)

### Scope

- [ ] 🐞 Bugfix (non-breaking changes que resuelve un problema
- [ ] 💚 Mejora (non-breaking change que agrega/modifica funcionalidad a una característica existente)
- [x] ⚡️ Nueva característica/feature (non-breaking change que agrega una nueva característica)
- [ ] ⚠️ Breaking change (cambio que no es compatible con versiones anteriores y/o cambia la funcionalidad actual)

2024-09-03 22:55 UTC, bryamaranguri approved these changes
¡Excelente trabajo!

2024-09-04 18:09 UTC, nayruthCalla requested changes
Hola Juan, buen trabajo pero por favor corrige los nombres los archivos, deben ser validos, sin esapcios, en minusculas y sin tidles.

2024-09-04 22:16 UTC, jlac8 commented
Listo!, archivos corregidos

2024-09-04 22:40 UTC, nayruthCalla approved these changes

2024-09-04 22:40 UTC, merged